Fix ERR_PACKAGE_PATH_NOT_EXPORTED
rhysd/remark-emoji pull request #28
Opened 2023-08-07 21:23 UTC by thetarnav

fixes #27

2023-08-08 12:57 UTC, rhysd requested changes

2023-08-08 12:57 UTC, rhysd commented on package.json
> +      "default": "./index.js"
Since `default` is a general fallback, `require` is better.

2023-08-08 13:04 UTC, rhysd commented
- [`index.js`](https://github.com/rhysd/remark-emoji/blob/master/index.js) is an ESM module file. Why does setting it as entry point of CJS work?
- How did you confirm your change is correct? I'd like to follow the same steps. I just tried the same change in my local repository directory, I got the following error. This error is consistent with the behaivor I mentioned in the first question.
  ```
  Uncaught:
  Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/rhysd/Develop/github.com/rhysd/remark-emoji/index.js not supported.
  Instead change the require of index.js in null to a dynamic import() which is available in all CommonJS modules.
      at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
      at new NodeError (node:internal/errors:399:5)
      at Module._extensions..js (node:internal/modules/cjs/loader:1282:19)
      at Module.load (node:internal/modules/cjs/loader:1113:32)
      at Module._load (node:internal/modules/cjs/loader:960:12)
      at Module.require (node:internal/modules/cjs/loader:1137:19)
      at require (node:internal/modules/helpers:121:18) {
    code: 'ERR_REQUIRE_ESM'
  }
  ```

2023-08-08 14:48 UTC, thetarnav commented
> * [`index.js`](https://github.com/rhysd/remark-emoji/blob/master/index.js?rgh-link-date=2023-08-08T13%3A04%3A04Z) is an ESM module file. Generally just `require()`ing ESM module file causes an import error. Why does setting it as entry point of CJS work?

I'm not using CJS. I think. Unless I'm misunderstanding something. The `remark` package works fine, this one does too. Only the exports were wrong for some reason.

> * How did you confirm your change is correct? I'd like to follow the same steps.

I just directly modified the package.json in node_modules until it worked for me [here](https://github.com/solidjs-community/solid-primitives/tree/main/site). But then I just reverted to 3.1.1, instead of patching the module.

For a better test I've made this: https://github.com/thetarnav/remark-emoji-export-issue
It installs `remark-emoji@3.1.2` with this patch applied, and everything works great for both node 18, 20; and typescript 5 and 4.

I'm not entirely sure how there exports are supposed to be setup, I usually just change them until everything works. But one thing I've noticed is that adding more conditions doesn't hurt, but may help :D

2023-08-08 16:10 UTC, rhysd commented
> I'm not using CJS. I think.

Then it is very weird because you only modified configuration for CJS in this PR.

It looks you're using TypeScript. Can you provide your tsconfig which is used for compiling scripts which imports remark-emoji?

2023-08-08 16:19 UTC, rhysd commented
From your example (thanks for the repository for clarification), your tsconfig looks

```json
{
  "compilerOptions": {
    "module": "ESNext",
    "target": "ESNext",
    "newLine": "LF",
    "moduleResolution": "node",
    "strict": true,
    "types": ["node"]
  }
}
```

https://github.com/thetarnav/remark-emoji-export-issue/blob/main/examples/jiti/tsconfig.json

The `"moduleResolution": "node"` is very legacy configuration and it only assumes CommonJS. So you're using CommonJS module resolution unexpectedly.

From https://www.typescriptlang.org/tsconfig#moduleResolution

> 'node10' (previously called 'node') for Node.js versions older than v10, which only support CommonJS require. You probably won’t need to use node10 in modern code.

You should use `node16`, `nodenext` or `bundler` which support both ESM and CJS.

2023-08-08 17:39 UTC, thetarnav commented
Alright, switching to NodeNext works for me too. shall I close the issue and PR then?

2023-08-09 01:48 UTC, rhysd commented
Thanks for confirming it. I'm closing this and the issue.

2023-08-09 01:48 UTC, closed without merging